-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 28, 2025 at 09:37 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kbs`
--

-- --------------------------------------------------------

--
-- Table structure for table `tempat_wisatakbs`
--

CREATE TABLE `tempat_wisatakbs` (
  `no` int(11) NOT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `vote_average` float DEFAULT NULL,
  `vote_count` int(11) DEFAULT NULL,
  `type` varchar(100) DEFAULT NULL,
  `htm_weekday` int(11) DEFAULT NULL,
  `htm_weekend` int(11) DEFAULT NULL,
  `maps` varchar(255) DEFAULT NULL,
  `lokasi` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `gambar` varchar(255) DEFAULT NULL,
  `outdoor_indoor` enum('indoor','outdoor') DEFAULT NULL,
  `usia` varchar(50) DEFAULT NULL,
  `kategori` varchar(255) DEFAULT NULL,
  `jenis_kelamin` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tempat_wisatakbs`
--

INSERT INTO `tempat_wisatakbs` (`no`, `nama`, `vote_average`, `vote_count`, `type`, `htm_weekday`, `htm_weekend`, `maps`, `lokasi`, `description`, `gambar`, `outdoor_indoor`, `usia`, `kategori`, `jenis_kelamin`) VALUES
(1, 'Candi Borobudur', 4.7, 81922, 'Sejarah', 50000, 50000, 'https://maps.app.goo.gl/mdMPxU2ssGcnxFP26', 'Magelang', 'Candi yang pernah masuk sebagai salah satu dari Tujuh Keajaiban Dunia ini dihiasi oleh banyak relief di dinding candi. Relief yang ada di Candi Borobudur mencapai 2.672 dan panjangnya bisa mencapai 6 kilometer', 'https://assets-a1.kompasiana.com/items/album/2021/04/28/tempat-wisata-sekitar-candi-borobudur-60893a04d541df5e5c65c512.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Anak, Keluarga'),
(2, 'Candi Prambanan', 4.7, 71751, 'Sejarah', 50000, 50000, 'https://maps.app.goo.gl/qszpHHMYF8TUsXiw5', 'Sleman', 'Candi Prambanan adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9 masehi. Candi ini dipersembahkan untuk Trimurti, tiga dewa utama Hindu yaitu Brahma sebagai dewa pencipta, Wisnu sebagai dewa pemelihara, dan Siwa sebagai dewa pemusnah. ', 'https://www.suwatu.id/wp-content/uploads/2021/06/CANDI-01-PRAMBANAN.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Anak, Keluarga'),
(3, 'Malioboro', 4.7, 3752, 'Wisata', 3000, 3000, 'https://maps.app.goo.gl/EpBYTaRM6czWyqKU8', 'Kota Yogyakarta', 'Malioboro adalah jantung Kota Jogja. Meskipun terkenal sebagai surga belanja cendera mata dan barang kerajinan, ternyata tak sedikit wisatawan dan orang lokal mendatangi Malioboro pagi-pagi sekali untuk berolahraga atau sekedar menikmati udara segar sambil mencari sarapan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP1Py54axiKqDSRU-bxlWx4gGzPaTrDMJz-Q&s', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Anak, Keluarga'),
(4, 'Gembira Loka Zoo', 4.5, 36337, 'Kebun Binatang', 60000, 80000, 'https://maps.app.goo.gl/rLNf35b2mRvgxxtK8', 'Kota Yogyakarta', 'Gambira Loka adalah kebun binatang yang berada di Yogyakarta. Berisi berbagai macam spesies dari belahan dunia, seperti orangutan, gajah asia, simpanse, harimau, dan lain sebagainya. Kebun Binatang Gembira Loka menjadi daya tarik tersendiri bagi para wisatawan Yogyakarta. Gembira Loka Zoo sempat rusak parah akibat gempa bumi yang mengguncang kota Yogyakarta tahun 2006. Tetapi, setelah direnovasi Kebun Binatang Gembira Loka tetap dicari para wisatawan.', 'https://cdn.antaranews.com/cache/1200x800/2016/11/20161127gembira_loka_zoo.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Anak, Keluarga'),
(5, 'Monumen Yogya Kembali', 4.5, 11302, 'Sejarah', 15000, 15000, 'https://maps.app.goo.gl/96b4HNtvRQZ9Rd6v5', 'Sleman', '\"Museum Monumen Jogja Kembali adalah sebuah museum Budaya dan Sejarah perjuangan kemerdekaan Republik Indonesia yang ada di kota Yogyakarta dan dikelola oleh Departemen Kebudayaan dan Pariwisata. Museum yang berada di bagian utara kota ini banyak dikunjungi oleh para pelajar dalam acara darmawisata. Museum Monumen dengan bentuk kerucut ini terdiri dari 3 lantai dan dilengkapi dengan ruang perpustakaan serta ruang serbaguna. Pada rana pintu masuk dituliskan sejumlah 422 nama pahlawan yang gugur di daerah Wehrkreise III (RIS) antara tanggal 19 Desember 1948 sampai dengan 29 Juni 1949. Dalam 4 ruang museum di lantai 1 terdapat benda-benda koleksi: realia', 'https://asset.kompas.com/crops/NulkwYRCDyUf0nkho6eXPqW8lnk=/0x0:999x666/1200x800/data/photo/2023/06/13/64882c8d0eca2.jpg', 'outdoor', 'semua usia', 'Liburan Bersejarah, Liburan Santai', 'Pria, Wanita, Keluarga'),
(6, 'Pantai Parangtritis', 4.5, 8727, 'Pantai', 6000, 6000, 'https://maps.app.goo.gl/wkmxVLL6QMV8GUqA7', 'Bantul', 'Paintai Parangtritis merupakan salah satu ikon di Kabupaten Bantul. Pantai ini memiliki pasir hitam. Di pantai ini dapat bermain ATV, menaiki kuda. Di sisi utara timur pantai dapat menemukan bukit kecil yang sangat cocok untuk menikmati pemandangan sore hari ditemani angin. pantai ini memiliki cerita misteri di dalamnya.', 'https://static.promediateknologi.id/crop/0x0:921x518/750x500/webp/photo/p1/995/2024/12/28/IMG89754621-3639294115.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(7, 'Tugu Yogyakarta', 4.8, 13330, 'Wisata', 0, 0, 'https://maps.app.goo.gl/xbniBPxiys64vfdj9', 'Kota Yogyakarta', 'Tugu ini sekarang merupakan salah satu objek pariwisata Yogyakarta, dan sering dikenal dengan istilah â€œTugu Pal Putihâ€ (pal juga berarti tugu), karena warna cat yang digunakan sejak dulu adalah warna putih. Tugu pal ini berbentuk bulat panjang dengan bola kecil dan ujung yang runcing di bagian atasnya. Jika dilihat dari Keraton Yogyakarta ke arah utara, maka akan terlihat bahwa Jalan Malioboro, Jalan Margo Utomo, Tugu Yogyakarta, dan Jalan A.M. Sangadji membentuk garis lurus menuju puncak Gunung Merapi yang dikenal sebagai Garis Imajiner Yogyakarta.', 'https://yogya.co/wp-content/uploads/tugu-jogja.webp', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(8, 'Fort Vredeburg Museum', 4.6, 15281, 'Sejarah', 3000, 3000, 'https://maps.app.goo.gl/FZSGTyN8ggiX6rWJ9', 'Kota Yogyakarta', 'Letak Benteng Vredeburg Yogyakarta di kawasan nol kilometer pusat Kota Yogyakarta menjadikan sebuah daya tarik bagi para wisatawan. Dalam pelayanannya kepada masyarakat, museum Benteng Vredeburg tidak lepas dari unsur-unsur pendidikan karena pada dasarnya museum memiliki dua fungsi yaitu sebagai rekreasi sekaligus tempat pendidikan. Informasi tentang keBudaya dan Sejarahan, kebudayaan dan nilai-nilai luhur kejuangan disampaikan kepada generasi muda dalam nuansa edutainment, yang berasal dari kata education dan entertainment. Demikianlah, Benteng Vredeburg yang sekarang menjadi Museum Benteng Vredeburg Yogyakarta telah melekat dengan Kota Yogyakarta. Latar belakang Budaya dan Sejarah Kota Yogyakarta baik sebagai ibukota Kasultanan Yogyakarta dan ibukota NKRI tidak dapat dipisahkan dengan Budaya dan Sejarah Benteng Vredeburg Yogyakarta. Pelestarian Benteng Vredeburg sebagai museum bukan berarti pengagungan simbol kejayaan kolonial. Akan tetapi tujuannya untuk mendapatkan fungsi baru yang dapat memberikan informasi dan aspirasi perjuangan nasional bagi generasi mendatang.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Fort_Vredeburg_gate.JPG/1200px-Fort_Vredeburg_gate.JPG', 'indoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(9, 'Taman Sari', 4.6, 27899, 'Wisata', 5000, 5000, 'https://maps.app.goo.gl/MK9CbLXi5fdcuExX9', 'Kota Yogyakarta', 'Taman Sari Yogyakarta, merupakan salah satu bangunan milik kesultanan Yogyakarta yang difungsikan sebagai destinasi wisata. Namun selain sebagai destinasi wisata, taman sari pada saat tertentu juga masih digunakan sebagai tempat ritual oleh keluarga raja. Dengan bentuk bangunan arsitektur ala Portugis-Jawa, bangunan di taman ini menjadi daya tarik utama. Meskipun sekarang kondisi bangunan tak lagi utuh seperti saat masih difungsikan sebagai taman kesultanan, namun tetap saja aura keindahan terpancar kuat dari bangunan bangunan di taman ini.', 'https://nagantour.com/wp-content/uploads/2023/07/taman-sari-yogyakarta-scaled.webp', 'outdoor', 'Semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(10, 'The Palace of Yogyakarta (Keraton Yogyakarta)', 4.6, 30091, 'Sejarah', 8000, 8000, 'https://maps.app.goo.gl/E8sTWXxfBZrHbw3S9', 'Kota Yogyakarta', 'Kompleks keraton merupakan museum yang menyimpan berbagai koleksi milik kesultanan, termasuk berbagai pemberian dari raja-raja Eropa, replika pusaka keraton, dan gamelan. Dari segi bangunannya, keraton ini merupakan salah satu contoh arsitektur istana Jawa yang terbaik, memiliki balairung-balairung mewah dan lapangan serta paviliun yang luas.', 'https://c8.alamy.com/comp/ED9PW5/interior-of-the-yogyakarta-kraton-royal-palace-in-java-indonesia-ED9PW5.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(11, 'Hutan Pinus Mangunan Dlingo', 4.6, 18271, 'Alam', 3000, 3000, 'https://maps.app.goo.gl/6Y3BVqcihG3PTD4v7', 'Bantul', 'hutan pinus mangunan yang ada di Jogja bisa menjadi destinasi hutan yang tepat. Disana banyak terdapat pepohonan yang tinggi menjulang, yang dikenal dengan nama Pinus Merkusi. Nggak heran deh kalau banyak wisatawan yang merasa kepincut dengan objek wisata ini, sebab kesejukan dan keindahan pemandangannya benar-benar mempesona mata.', 'https://i0.wp.com/www.ratunyatravel.com/wp-content/uploads/2021/12/hutan-pinus-mangunan-768x512.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(12, 'Jogja Bay', 4.4, 16877, 'Wisata Air', 90000, 100000, '1.104.188.754', 'Sleman', 'Jogja Bay Waterpark (JBW) salah satu waterpark terbesar di asia tenggara yang berlokasi di kota wisata terbesar kedua di Indonesia yaitu Yogyakarta. Dan belakangan ini sudah menjadi salah satu tujuan destinasi wisata di Yogyakarta. Waterpark yang saat ini merupakan atraksi wahana air terbesar, terlengkap berstandar internasional dan memiliki karakter Bajak Laut â€“ dengan bangga menyampaikan sesuai TripAdvisor Internasional telah merilis tahun 2019 â€œJogja Bay Waterpark di Yogyakarta sebagai Waterpark Terbaik ke 3 di Asiaâ€. Jogjabay telah tersertifikasi CHSE (Clean, Health, Safety, & Enviroment) dengan score 100% dari Kemenparekraf RI dan Sucofindo.', 'https://imgcdn.espos.id/@espos/images/2019/11/utama.jpg?quality=60', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Air, Taman Hiburan', 'Pria, Wanita, Keluarga'),
(13, 'Pantai Goa Cemara', 4.3, 12755, 'Pantai', 4000, 4000, '110.248.963', 'Bantul', 'Adalah Kawasan Wisata Terpadu, satu pintu dengan pembagian area yang jelas. Public area memang seperti diutamakan di pantai ini. Jajaran pedagang lokal berpadu dengan ramainya pasar tradisional. Dengan area cakupan luas meliputi wilayah konservasi penyu hijau, wilayah lahan pertanian, daerah wisata, dan pelestarian hutan cemara. Pasar tradisional, wisata pantai, outbond, camping ground, ruang pertemuan, atv, jip wisata offroad gumukpasir, kuliner, dan cinderamata. Dengan dukungan fasilitas publik yang lengkap dan terus berkembang. Fasilitas publik seperti MCK, kantor sekretariat, kantor keamanan, posko SAR, rumah ibadah, pos kesehatan juga tersedia.', 'https://happytour.id/wp-content/uploads/2018/07/PantaiGoaCemara1.jpg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(14, 'Museum Perjuangan', 4.5, 836, 'Sejarah', 1000, 1000, '1.103.718.611', 'Kota Yogyakarta', 'Museum Perjuangan memiliki tempat utama yang berisi peninggalan Budaya dan Sejarah. Ruangan yang pertama di taat secara rapi di luar gedung. Disana menyajikan patung kepala pahlawan nasional, relief yang menjelaskan dan bercerita bagaimana lahirnya Boedi Utomo, masa penjajahan Jepang, dan partai Sarekat Islam. Selain itu juga membahas PD dua, Kongres Pemuda kesatu, masa pindahnya Ibukota negara ke Jogja, Peristiwa 1 Maret 1949, dan pertempuran puputan di Bali.', 'https://raskita.com/wp-content/uploads/2019/09/Museum-Perjuangan.jpg', 'indoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(15, 'Lava Merapi and Alien Stone', 4.5, 8111, 'Alam', 350000, 350000, '1.104.552.585', 'Sleman', 'Lava Tour Merapi bisa menjadi pilihan aktivitas wisata ketika berlibur di Yogyakarta. Lava Tour Merapi adalah istilah untuk tur wisata kawasan terdampak erupsi Gunung Merapi tahun 2010. Tur yang dimaksud saat ini merupakan tur menggunakan mobil jenis jeep. Kegiatan tur meliputi kunjungan ke sejumlah titik yang terkena dampak langsung erupsi. Lava tour Merapi ditawarkan sebagai aneka pilihan paket wisata. Paket-paket ini dibanderol dengan harga yang beragam. Setiap paket sudah termasuk tiket masuk untuk sejumlah titik pemberhentian. Paket wisata ini bisa menampung rombongan, sehingga cocok untuk dijajal sebagai liburan keluarga atau bersama teman.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-n_6-mKrx_wBB-qx8LkgeP_2ENPdr8eJsHQ&s', 'outdoor', 'Oct-50', 'Liburan Keluarga, Liburan Santai, Wisata Atraksi', 'Pria, Wanita, Keluarga'),
(16, 'Taman Wisata Kaliurang', 4.4, 5217, 'Alam', 8000, 8000, '11.042.636', 'Sleman', 'Taman Wisata Kaliurang dapat menjadi referensi wisata akhir pekan keluarga. Pemandangan sekitar sangatlah indah, masih banyak pepohonan yang tumbuh tinggi menjulang. Ditambah lagi pemandangan puncak Gunung Merapi yang gagah. Selain itu, udara di sekitar pun masih sangat sejuk. Aroma asap kendaraan bermotor pun tidak tercium di kawasan ini. Berada di sini membuat paru â€“ paru menjadi lebih sehat. Banyak wisatawan yang datang bersama keluarga. Duduk santai beralaskan tikar di atas rerumputan sambil bercengkerama dengan keluarga. Ditambah lagi, suasana yang sangat mendukung untuk beramah â€“ tamah. Selain menyuguhkan pemandangan yang indah, Taman Wisata Kaliurang pun memiliki wahana outbound. Seperti flying fox hingga rumah pohon Ridz High Rope.', 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/222/2024/09/02/WhatsApp-Image-2024-09-02-at-151307-3886037575.jpeg', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Anak, Keluarga'),
(17, 'Pantai Ngobaran', 4.5, 3288, 'Pantai', 5000, 5000, '1.105.050.409', 'Gunung Kidul', 'Keunikan yang menjadi ciri khas Pantai Ngobaran adalah adanya Pura dan Arca. Keberadaannya membuat sekilas Pantai Ngobaran memiliki suasana khas yang mirip dengan Pulau Bali. Satu keunikan yang kemungkinan besar tersembunyi dari kebanyakan wisatawan adalah adanya sumber air tawar di tepi laut. Namun aliran air tawar hanya bisa ditemukan ketika air laut sedang surut. Satu sajian spesial yang bisa didapatkan di Pantai Ngobaran adalah landak laut atau bulu babi. Kuliner ini bisa dipesan di warung-warung yang ada di sekitar pantai. Bagian landak laut yang dimakan adalah dagingnya.', 'https://awsimages.detik.net.id/community/media/visual/2024/08/07/pantai-ngobaran_169.png?w=1200', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(18, 'Museum HM Soeharto', 4.4, 2628, 'Sejarah', 50000, 50000, '1.102.805.284', 'Bantul', 'Museum Soeharto adalah adalah bangunan berBudaya dan Sejarah berbentuk museum yang menyimpan memoar dan peninggalan-peninggalan Jenderal Besar TNI Soeharto yang diresmikan pada tahun 2013. Museum ini berdiri di atas tanah milik Soeharto yang terletak di Dusun Kemusuk Lor, Desa Argomulyo, Kecamatan Sedayu, Kabupaten Bantul, Daerah Istimewa Yogyakarta. Di dalam memorial ini, terdapat sebuah bangunan joglo besar di pusat lokasi, rumah kakek buyut Pak Harto yaitu Notosudiro. Terdapat juga barang-barang peninggalan, diorama Budaya dan Sejarah kehidupan pak Harto,  dokumen arsip nasional, video, dan beberapa foto yang berkaitan dengan Budaya dan Sejarah Pak Harto. ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTXLpFxm4w6tGYxs7ZcSgrc2rruyHt_CQtvg&s', 'indoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(19, 'Museum Monumen Pangeran Diponegoro', 4.4, 1778, 'Sejarah', 50000, 50000, '1.103.514.473', 'Kota Yogyakarta', 'Museum Monumen Pangeran Diponegoro adalah museum sekaligus monumen kediaman Pangeran ketika dikepung oleh pihak Belanda. Museum ini berisi berbagai peninggalan Pangeran Diponegoro. Di museum ini juga terdapat pendapa dan pringgitan yng didalamnya berisi benda-benda berBudaya dan Sejarah.  Benda berBudaya dan Sejarah tersebut berupa berbagai jenis senjata tradisional seperti keris, tombak, pedang, panah, dan masih banyak lagi senjata yang dikoleksi di dalam museum ini. i Museum Monument Pangeran Diponegoro ini juga terdapat dinding yang berlubang yang menjadi jalan keluar Pangeran Diponegoro untuk bisa lolos dari kepungan penjajah Belanda. Di museum ini juga terdapat barang peninggalan milik Sri Sultan Hamengku Buwono II yaitu ketipung dan wilahan bonang penembung yang terbuat dari kayu dan perunggu yang berwarna merah dan kuning, barang peninggalan Sri Sultan HB II yang ada mencapai lebih dari 100 buah. Disana juga terdapat dua senjata meriam yang terletak di depan dan disebelah timur pendopo, serta ada berbagai macam peralatan rumah tangga seperti tempat menaruh siri, canting, teko dan bokor.', 'https://harrismaul.com/wp-content/uploads/2017/08/monumen2.jpg', 'indoor', 'semua usia', 'Liburan Keluarga, Liburan Santai, Wisata Sejarah', 'Pria, Wanita, Keluarga'),
(20, 'Pantai Ngrumput', 4.6, 1437, 'Pantai', 10000, 10000, '1.105.831.238', 'Gunung Kidul', 'Pantai Ngrumput memang kalah pamor dengan Parangtritis. Namun, urusan eksotisme, pantai yang terletak di Gunung Kidul itu tak bisa disepelekan begitu saja. Karena belum begitu dikenal oleh masyarakat, pantai ini seolah belum terjamah. Sehingga keindahan alamnya masih alami dan juga bersih karena terhindar dari sampah. Selain itu wisatawan yang datang kemari bisa merasakan memiliki pantai pribadi karena masih sepi pengunjung. Eksotisme pertama dari Pantai Ngrumput di mata para wisatawan adalah tepi pantainya. Seperti halnya Pantai Gunung Kidul lainnya yang terkenal dengan pasir putihnya, demikian juga dengan pantai ini. Istimewanya, banyak wisatawan tak ingin beranjak dari pasir tersebut hingga memilih untuk bermalam. Biasanya kegiatan camping itu selalu identik dengan mendaki gunung. Kali ini, tanpa perlu mendaki wisatawan dapat merasakan sensasi bermalam di bawah sinar rembulan. Kegiatan ini yang membuat Pantai Ngrumput ini makin popular di mata wisatawan.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6ebnspxVf2-ULhRPCmIO7aEc91l5fG1OJGA&s', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(21, 'Nol Kilometer Jl.Malioboro', 4.7, 565, 'Wisata', 0, 0, '1.103.647.652', 'Kota Yogyakarta', 'Titik Nol Kilometer Jogja adalah sebuah patung landmark di tengah kota Yogyakarta yang menandakan titik awal pengukuran jarak di kota ini. Patung ini terletak di persimpangan Jalan Ahmad Yani dan Jalan Panglima Sudirman, yang berada di dekat Tugu Yogyakarta.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3d2Wtp5EQHkw0hx0sOVXJTkk4hADpz9-iMQ&s', 'outdoor', 'semua usia', 'Liburan Keluarga, Liburan Santai', 'Pria, Wanita, Keluarga'),
(22, 'Museum Sandi', 4.7, 1182, 'Sejarah', 25000, 25000, '1.103.711.548', 'Kota Yogyakarta', 'Museum Sandi adalah museum satu-satunya yang menyimpan alat-alat untuk mengirim pesan rahasia. Museum ini juga merekam segala jenis persandian di Indonesia bahkan dunia, jadi jika anda yang suka memecahkan sandi maka museum ini adalah tempat yang cocok untuk anda kunjungi. Setiba anda di loby museum sandi akan disambut hangat oleh pengelola museum sandi, orang-orangnya ramah, baik dan legowo banget. Pada masa itu museum sandi ini adalah museum yang mengoleksi segala jenis benda dan alat untuk memecahkan sandi mulai dari telegraf, buku kode sandi sampai mesin-mesin sandi yang terbuat di Indonesia maupun luar negeri.', 'https://kebudayaan.jogjakota.go.id/assets/instansi/kebudayaan/article/20210904114453.jpeg', 'indoor', 'semua usia', 'Liburan, Pendidikan, Wisata Sejarah', 'Pria, Wanita, Pendidikan'),
(23, 'Taman Pintar Yogyakarta', 4.5, 4846, 'Buatan', 20000, 20000, '1.103.678.697', 'Kota Yogyakarta', 'Taman Pintar Yogyakarta adalah wahana wisata yang terdapat di pusat Kota Yogyakarta, tepatnya di Jalan Panembahan Senopati No. 1-3, Yogyakarta, di kawasan Benteng Vredeburg. Taman ini memadukan tempat wisata rekreasi maupun edukasi dalam satu lokasi. tempat rekreasi ini sangat baik untuk anak-anak dalam masa perkembangan. taman ini, khususnya pada wahana pendidikan anak usia dini dilengkapi dengan teknologi interaktif digital serta pemetaan video yang akan memacu imajinasi anak serta ketertarikan mereka terhadap teknologi', 'https://www.1001malam.com/travel/wp-content/uploads/2016/08/Taman-Pintar-Sumbre-afiaanwas-blogspotcom.jpg', 'indoor', 'semua usia', 'Liburan, Pendidikan', 'Pria, Wanita, Pendidikan'),
(24, 'Blue Lagoon Jogja', 4.3, 3585, 'Wisata Air', 3000, 3000, '11.045.026', 'Sleman', 'Blue Lagoon Jogja merupakan salah satu obyek wisata yang di jadikan tempat pemandian sumber mata air ini yang muncul dari permukaan tanah di dalam kolam. Apabila Anda melihat ke dalam kolam akan terlihat gelembung-gelembung kecil yang muncul dari permukaan tanah. Hal itu menunjukkan bahwa terdapat air yang terus menerus muncul dari permukaan tanah tersebut. Meskipun Blue Lagoon di Jogja ini sudah lama namun tempat wisata ini mulai tenar dipertengahan tahun 2014. Pemandian Blue Lagoon ini terletak di Desa Dalem, Widodomartani, Ngemplak, Sleman, Yogyakarta', 'https://visitingjogja.jogjaprov.go.id/wp-content/uploads/2020/04/672.jpg', 'outdoor', 'semua usia', 'Liburan', ''),
(25, 'Desa Wisata Pentingsari', 4.4, 855, 'Wisata', 20000, 20000, '1.104.296.004', 'Sleman', 'Desa Wisata Pentingsari terletak di lereng Gunung Merapi, sekitar 22,5 kilometer dari pusat Kota Yogyakarta. Desa ini dikenal di mancanegara sebagai salah satu desa wisata dengan segudang penghargaan. Dusun Pentingsari berbentuk seperti semenanjung dimana sebelah barat terdapat lembah yang sangat curam yaitu kali Kuning dan sebelah selatan terdapat lebah yang berupak Goa Ledok / Ponteng dan Gondoran sebelah timur terdapat lembah yang curam yaitu Kali Pawon dan sebelah utara merupakan dataran yang dapat berhubungan langsung dengan tanah di sekeliling kelurahan Umbulharjo sampai ke pelataran gunung Merapi. Dusun Pentingsari terdiri dari dua dusun yaitu Bonorejo dan Pentingsari. Ada beberapa program wisata desa, seperti live in, kemah, trekking, atau outbound yang bisa dinikmati. Untuk kegiatan wisata budaya, wisatawan bisa mengikuti kegiatan, seperti belajar gamelan, menari, membatik, membuat wayang rumput, dan membuat janur.', 'https://desawisatapentingsari.com/wp-content/uploads/2025/03/Landmark-Pentingsari-1024x461.jpeg', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(26, 'Desa Wisata Gamplong', 4.4, 841, 'Wisata', 5000, 5000, '1.102.374.676', 'Sleman', 'Berada di Kabupaten Sleman, tepatnya 16 kilometer dari titik nol Yogyakarta. Tempat wisata yang sering dijuluki mini Hollywood ini menawarkan berbagai desain bangunan unik. Sangat cocok bagi wisatawan yang menyukai fotografi.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(27, 'Museum Perjuangan', 4.5, 836, 'Sejarah', 1000, 1000, '1.103.718.611', 'Kota Yogyakarta', 'Museum Perjuangan memiliki tempat utama yang berisi peninggalan Budaya dan Sejarah. Ruangan yang pertama di taat secara rapi di luar gedung. Disana menyajikan patung kepala pahlawan nasional, relief yang menjelaskan dan bercerita bagaimana lahirnya Boedi Utomo, masa penjajahan Jepang, dan partai Sarekat Islam. Selain itu juga membahas PD dua, Kongres Pemuda kesatu, masa pindahnya Ibukota negara ke Jogja, Peristiwa 1 Maret 1949, dan pertempuran puputan di Bali.', '', 'indoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(28, 'Geoforest Watu Payung Turunan', 4.5, 796, 'Alam', 5000, 5000, '1.104.362.646', 'Gunung Kidul', 'Nama Watu Payung merujuk kepada sebuah batu yang bentuknya mirip dengan bentuk payung. Kata Watu dalam bahasa jawa berarti Batu. Sedangkan kata Payung, yang bermakna Payung. Keberadaan batu yang menyerupai payung tersebut di kawasan hutan konsevasi, menjadikan sebuah kunjungan wisata alam yang sangat menyenangkan. Suasana yang teduh, nuansa alam, udara yang sejuk, bernilai edukatif, adalah daya tarik dari Watu Payung Turunan.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(29, 'Museum Sonobudoyo Unit I', 4.6, 1711, 'Sejarah', 3000, 3000, '1.103.639.555', 'Kota Yogyakarta', 'Museum Sonobudoyo unit pertama yang ada di dekat Alun-Alun Keraton Yogyakarta yang memiliki bentuk seperti bangunan rumah joglo dengan gaya Masjid Keraton Kasepuhan Cirebon. di museum ini terdapat koleksi alat musik seperti replika andong, wayang Rama, Sinta dan juga Lesmana, Anoman hingga Rahwana. Kemudian koleksi keris, koleksi batik dan koleksi buku kebudayaan.', '', 'indoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(30, 'Museum Factory Dan Kedai Chocolate Monggo', 4.6, 1704, 'Agrowisata', 15000, 15000, '110.298.431', 'Bantul', 'Disini wisatawan dapat belajar mengenai Budaya dan Sejarah cokelat, melihat langsung pembuatan cokelat di pabrik, dan langsung bisa mempraktekkan membuat cokelat. Cokelat Monggo ini dibuat dari warga negara Belgia, yang terinspirasi karena rasa rindunya akan rasa cokelat Belgia.', '', 'indoor', 'semua usia', 'Liburan, Keluarga', ''),
(31, 'Kawasan Pantai Baron', 4.4, 1698, 'Alam', 10000, 10000, '1.105.487.763', 'Gunung Kidul', 'Objek wisata Pantai Baron merupakan pantai yang membentuk cekungan. Seperti pantai lainnya, di Pantai Baron tersedia aneka ikan laut beserta olahannya. Ikan yang biasanya dijual di Pantai Baron adalah udang windu, kakap, bawal putih dan tongkol. Pantai Baron memiliki fasilitas berupa tempat pelelangan ikan, wahana permainan anak-anak, perahu bermesin, dan toko cenderamata. Buah sirkaya, pisang tanduk, sirsak, dan berbagai macam cenderamata yang terbuat dari kerang laut.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(32, 'Kids Fun Galleria Mall', 4.4, 1693, 'Buatan', 60000, 60000, '1.103.791.605', 'Kota Yogyakarta', 'Kids Fun cabang Galeria Mall menawarkan tema Wild Wild West yang membawa kita ke dunia barat dimana kaum koboi dan Indian bertemu. Tidak hanya sekedar nama, desain interiornya pun disesuai dengan tema yang diusung. Di beberapa bagian diletakkan patung koboi dan Indian untuk memperkuat suasana. Belum lagi area counter yang sekilas mirip bar di film-film bertema sejenis.', '', 'indoor', 'semua usia', 'Liburan, Keluarga', ''),
(33, 'Taman Bunga Amarilis', 4.2, 1641, 'Agrowisata', 10000, 10000, '1.104.991.167', 'Gunung Kidul', 'Taman Bunga Amarlis dapat dikatakan wisata tahunan, karena bunga mekar setiap tahun. Namun, jangka mekarnya sangat pendek, sehingga pengunjung harus segera datang ketika mekar. Dan dari tahun ke tahun, kondisi taman bunga sudah semakin baik. Jalan setapak yang sudah rata dengan semen telah disediakan. Sehingga, pengunjung tidak perlu khawatir becek atau kotor karena tanah. Taman pun telah dibentuk dengan kotak-kotak yang membuatnya tampak tertata rapi. Taman bunga telah dilengkapi dengan jalan setapak yang membantu akses pengunjung lebih dekat dengan bunga. Jadi, angle ketika berfoto lebih terlihat indah. Taman bunga juga dibentuk sehingga tidak monoton hanya satu lahan seperti sawah.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(34, 'Tegaldowo Puspa Gading Park', 4.4, 1635, 'Buatan', 10000, 10000, '1.103.228.654', 'Bantul', 'Satu lagi obyek wisata alternatif karya dari warga hadir di Kabupaten Bantul, destinasi baru tersebut telah menjadi viral di media sosial (medsos) namanya Taman Puspa Gading berlokasi di Dusun Tegaldowo, Dukuh Grojogan, Kecamatan Bantul, Bantul, DIY. Taman Puspa Gading berada di pinggiran sungai Bedog, selain berupa taman untuk berswafoto berlatar belakang hamparan sawah dengan berhiaskan patung kadal raksasa dan jembatan gantung yang membentang di atas sungai. Taman Puspa Gading juga memiliki beberapa wahana permainan anak, diantaranya kolam renang, mandi bola, terapi ikan, foto dengan badut kelinci, motor apv, menangkap ikan, dan wahana melukis.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(35, 'Bukit Teletubbies', 4.1, 1173, 'Alam', 2000, 2000, '110.511.764', 'Sleman', 'Wisata satu ini merupakan wisata yang lokasinya berada di pedesaan. Bukit satu ini tepatnya berada di Desa Sumberharjo, Prambanan, Kabupaten Sleman. Meski berada di pedesaan, Bukit Teletubbies Jogja ini juga sama dengan wisata lain yang memiliki ciri khas dan keunikan tersendiri. Pemandangan yang ditawarkan kawasan perbukitan ini cukup enak dipandang. Plus, kamu juga mendapatkan foto bagus dengan latar belakang perbukitan yang hijau. Bukit ini diberi nama Teletubbies karena adanya gardu panjang yang lokasinya berada di atas. Gardu ini kebetulan lokasinya berada di di timur rumah Domes. Rumah di dekat gardu ini bentuknya setengah bulat dan mirip rumah di serial Teletubbies. Sehingga, rumah itu disebut rumah Teletubbies', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(36, 'Pantai Watulawang', 4.6, 1166, 'Alam', 5000, 5000, '1.106.177.335', 'Gunung Kidul', 'Seperti halnya pantai-pantai lain di Gunung Kidul pantai ini banyak terdapat karang dan ombak yang besar, namun yang menjadikannya unik, terdapat karang yang cukup besar dan bisa digunakan untuk memandang ke arah lautan, warga sekitar atau pengelola membuat jembatan yang terbuat dari bambu yang digunakan untuk menyeberang ke karang agar pengunjung dapat menuju ke atas karang dengan aman. Suasana pantai ini masih tergolong sepi, dan banyak terdapat karang-karang besar di bibir pantai, bisa anda gunakan untuk foto-foto dengan teman, pacar, atau keluarga. Pasir pantai termasuk luas dengan warna putih kecokelatan, khas pasir pantai selatan jogja. Bersebalahan langsung dengan goa watulawang.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(37, 'Ngobaran Beach', 4.6, 1160, 'Alam', 5000, 5000, '1.105.028.785', 'Gunung Kidul', 'Nama Pantai Ngobaran yang unik ini tentu tak lepas dari cerita masalalu.Kisahnya berawal dari Kerajaan Majapahit dan Kerajaan Demak.Sekitar tahun 2003 lalu, bangunan berupa gapura dan patung-patung simbol agama Hindu dan Budha didirikan. Tujuannya untuk menghormati kedatangan keturunan Raja Brawijaya V di pantai tersebut. Tak hanya gapura, prasasti dan beberapa arca saja, tapi Anda juga akan menemukan bangunan Joglo dengan aliran Kejawen.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(38, 'Candi Banyunibo', 4.5, 1151, 'Sejarah', 5000, 5000, '1.104.940.734', 'Sleman', 'Candi Banyunibo adalah candi Buddha yang berada tidak jauh dari Candi Ratu Boko, yaitu di bagian sebelah timur dari Kota Yogyakarta ke arah Kota Wonosari. Candi ini terdiri atas satu candi induk yang menghadap ke barat dan enam candi perwara yang berbentuk stupa disusun berderet, tiga candi perwara di sisi selatan dan tiga candi perwara di sisi timur candi induk. Lokasinya yang dikelilingi oleh persawahan menjadikan candi Banyunibo sebagai salah satu alternatif tempat wisata yang wajib dikunjungi. Karena selain udara di sekitar candi yang masih alami, pengunjung juga bisa mempelajari tentang kekayaan keyakinan manusia Indonesia di masa lampau.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(39, 'Pantai Nglolang', 4.3, 1123, 'Pantai', 10000, 10000, '110.562.855', 'Gunung Kidul', 'Pantai ini sangat indah dengan pasir putih dan ombak yang bergulung-gulung dan menghempas karang ini masih terbilang sepi. Dan mengunjungi pantai yang masih sepi ini pastinya obat yang sangat manjur untuk menghilangkan kejenuhan. Setelah sehari-hari berkutat dengan kesibukan, deburan ombak yang menggulung-gulung dan menghempas karang, dan pemandangan cakrawala jauh di depan menjadi obat penetral suasana hati yang ampuh. Apalagi pemandangan di sekitar pantai ini dipercantik dengan dua tebing yang mengapit pantai.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(40, 'Pantai Kuwaru', 4.1, 1109, 'Pantai', 10000, 10000, '1.102.265.599', 'Bantul', 'Pantai Kuwaru terkenal dengan wisata yang terkesan santai dan murah.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(41, 'Puncak Suroloyo', 4.4, 1105, 'Alam', 5000, 5000, '1.101.810.727', 'Magelang', 'Selain cocok untuk menyaksikan keindahan matahari terbenam, Puncak Suroloyo juga terletak di ujung hamparan Pegunungan Menoreh yang membatasi Provinsi Jawa Tengah dan Daerah Istimewa Yogyakarta, tepatnya Kabupaten Kulon Progo dengan Magelang. Berada di Puncak Suroloyo seolah sedang berada di atap benteng raksasa yang berwarna hijau. Hal itu wajar karena Pegunungan Menoreh tampak memanjang bagai benteng yang membatasi Kabupaten Magelang dengan Kulon Progo. ', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(42, 'Ramadanu flower garden', 4.2, 1087, 'Agrowisata', 5000, 5000, '1.102.879.467', 'Magelang', 'Nama Ramadanu tediri dari dua kata, yakni Rama dan Danu. Rama digunakan karena taman ini dibuka pada bulan Ramadan, sementara Danu dari nama dusun Danurojo.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(43, 'Jogja Exotarium', 4.4, 746, 'Buatan', 20000, 20000, '110.358.356', 'Sleman', 'Di Mini Zoo Jogja Exotarium pengunjung dapat menyaksikan aneka satwa seperti reptil, hewan nocturnal, kelinci. Pengunjung dapat pula melakukan aktivitas seperti memancing, belajar berkuda atau memanah. Selain itu terdapat pula berbagai spot selfie, playground anak atau outbound. .Kehadiran Mini Zoo Jogja Exotarium yang dikemas sebagai taman wisata edukasi diharapkan menjadi wahana pengetahuan tentang satwa atau binatang.', '', 'indoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(44, 'Museum Kereta Karaton', 4.7, 735, 'Sejarah', 0, 0, '1.103.627.375', 'Kota Yogyakarta', '-', '', 'indoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(45, 'Watu Payung', 4.4, 730, 'Pantai', 0, 0, '110.520.934', 'Sleman', '-', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(46, 'Goa Rancang Kencono', 4.3, 719, 'Alam', 15000, 15000, '', 'Gunung Kidul', '-', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(47, 'Sumur Gumuling', 4.5, 718, 'Sejarah', 10000, 10000, '1.103.591.825', 'Klaten', 'Sumur Gumuling adalah salah satu tempat untuk ibadah atau kegiatan agama pada masa lalu. Sumur Gumuling merupakan masjid pada zaman pemerintahan Sri Sultan Hamengkubuwana I dan II', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(48, 'Kali Talang', 4.5, 716, 'Alam', 10000, 10000, '1.104.606.903', 'Klaten', 'Kali Talang berada di ketinggian sekitara 1.160 meter di atas permukaan laut (MDPL). Dari Kali Kalang, puncak Merapi seakan begitu dekat dengan panorama vegetasi di kawasan Taman Nasional Gunung Merapi. Objek wisata yang berada di perbatasan Jawa Tengah (Jateng) dan DIY itu menjadi salah satu spot terbaik untuk mengabadikan puncak Merapi.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(49, 'Kawasan Ekowisata Gunung Api Purba Nglanggeran', 4.5, 709, 'Alam', 30000, 30000, '1.105.415.759', 'Gunung Kidul', 'Kawasan Ekosistem Gunung Purba Nglanggeran atau yang biasa disebut Gunung Nglanggeran ini merupakan kawasan yang litologinya disusun oleh material vulkanik tua, berbentuk gunung batu raksasa yang membentang sepanjang kurang lebih 800 meter dengan tinggi mencapai 300 meter. Gunung Nglanggeran dinyatakan sebagai gunung api purba dari hasil penelitian dan refrensi yang ada. Sekitar 60-70 juta tahun yang lalu Gunung tersebut merupakan gunung berapi aktif.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(50, 'Pantai Ngetun', 4.5, 709, 'Pantai', 15000, 15000, '1.106.526.446', 'Gunung Kidul', 'Pantai Ngetun adalah keindahan yang sempurna dari Yogyakarta khususnya Gunung Kidul. Keindahan biota lautnya memang tidak bisa dihindarkan', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(51, 'Desa Wisata Tinalah (Dewi Tinalah - Wisata Jogja)', 4.3, 701, 'Wisata', 0, 0, '110.195.883', 'Kulon Progo', '-', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(52, 'Selopamioro Adventure Park', 4.5, 696, ' Wisata Air', 30000, 30000, '1.104.266.714', 'Bantul', 'Kegiatan outbond di lokasi Selopamioro Adventure Park sangat memanjakan para konsumen untuk menikmati alam. Fasilitas outbond berupa permainan air dan darat dari level anak anak sampai dengan dewasa bisa menjadi rekomendasi anda dan rekan kerja selanjutnya untuk mencoba outbond di Selopamioro Adventure Park.', '', 'outdoor', 'semua usia', 'Liburan, Keluarga, Pendidikan', ''),
(53, 'Goa Kebon', 4.3, 659, 'Wisata', 5000, 5000, '1.101.866.704', 'Kulon Progo', '-', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', ''),
(54, 'EMBUNG JETIS SURUH', 4.2, 651, 'Wisata', 5000, 5000, '1.103.845.035', 'Sleman', '-', '', 'outdoor', 'semua usia', 'Liburan, Keluarga', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tempat_wisatakbs`
--
ALTER TABLE `tempat_wisatakbs`
  ADD PRIMARY KEY (`no`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tempat_wisatakbs`
--
ALTER TABLE `tempat_wisatakbs`
  MODIFY `no` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=55;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
